apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-stress
  template:
    metadata:
      labels:
        app: cpu-stress
    spec:
      containers:
        - name: stress
          # TODO: figure out why this isn't producing anything
          # image:  ghcr.io/patrickpichler/stress-ng:latest
          image: polinux/stress:latest
          command: ["stress"]
          args: ["--cpu", "1"]
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 200m
