apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-stress
  template:
    metadata:
      labels:
        app: cpu-stress
    spec:
      containers:
        - name: stress
          image:  ghcr.io/patrickpichler/stress-ng:latest
          command: ["stress-ng"]
          args: ["--cpu", "1"]
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 200m
