apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-stress
  template:
    metadata:
      labels:
        app: cpu-stress
    spec:
      containers:
        - name: stress
          # stress-ng is stripped sadly and doesn't show any stack traces
          # image:  ghcr.io/colinianking/stress-ng:latest
          image:  polinux/stress
          command: ["stress-ng"]
          args: ["--cpu", "1"]
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 200m
