apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/securityContext/procMount
        value: Unmasked
    target:
      group: apps
      version: v1
      kind: DaemonSet
      name: ebpf-profiler
