apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ebpf-profiler
spec:
  selector:
    matchLabels:
      app: ebpf-profiler
  template:
    metadata:
      labels:
        app: ebpf-profiler
    spec:
      hostPID: true
      containers:
        - name: profiler
          image: ghcr.io/patrickpichler/otel-ebpf-profiler-kind-playground:latest
          command: ["/usr/local/bin/ebpf-profiler", "-collection-agent", "otel-collector-service:4317", "-no-kernel-version-check", "-disable-tls", "-v"]
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          volumeMounts:
            - name: kernel-debug
              mountPath: /sys/kernel/debug
            - name: proc
              mountPath: /proc
            - name: cgroup
              mountPath: /sys/fs/cgroup
      volumes:
        - name: kernel-debug
          hostPath:
            path: /sys/kernel/debug
        - name: proc
          hostPath:
            path: /proc
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
